### ISSUE TITLE
External identifiers other than PubMed ID

### ISSUE THREAD

**Issue by mrdsaunders** [tomwrobel/ora_data_model#150]
Can you confirm what should happen to non-PMID external identifiers in the deposit crosswalk?

e.g. should a WoS lite isidoc crosswalk to either or none of:

'<mods:identifier type="source_identifier">KW269</mods:identifier>'
'<mods:identifier type="isidoc">KW269</mods:identifier>'

From mapping doc:
```
<symplectic_field name="external-identifiers">
            <if test="scheme is pubmed"><ora_field>identifier_pmid</ora_field></if>
            <if test="scheme is other"><ora_field>record_identifers__record_identifier</ora_field><ora_note>Identifiers with a mapping specified in the ORA Data Model should be mapped using those fields. The value of @scheme should be mapped to record_identifiers__record_identifier_scheme</ora_note></if>
</symplectic_field>
```

**Comment by tomwrobel** [comment]
it should be

```
<mods:identifier type="isidoc">KW269</mods:identifier>
```

**Comment by tomwrobel** [comment]
@mrdsaunders is this enough or do you need more. Please close this ticket when you're done :)

**Comment by mrdsaunders** [comment]
For object `955388` in the test METS I get:
`<mods:identifier type="isidoc">GL0AU</mods:identifier>`

However on deposit it is not available in Sword output.

Can you check the ingesting please?

**Comment by mrdsaunders** [comment]
Hi Tom as you have been very busy clearing down GitHub issues but not this one, can I just check you have seen it?

**Comment by tomwrobel** [comment]
I’ll check on Monday!

**Comment by mrdsaunders** [comment]
Bump

**Comment by tomwrobel** [comment]
I'll check on Monday (sorry!)

**Comment by tomwrobel** [comment]
@mrdsaunders it's being ingested but not making it into the outbound Sword crosswalk, will fix

**Comment by tomwrobel** [comment]
Fixed in [feature/ora_customizations ab5f1e3] Send record identifiers in output
 confirmed fix on redeposit of 955388

**Comment by tomwrobel** [comment]
please close when QAd

**Comment by mrdsaunders** [comment]
Hi Tom I am still experiencing this issue e.g. `666229` `uuid_afb03abe-f056-44d0-aea6-fca8e262ea1f`

**Comment by tomwrobel** [comment]
@mrdsaunders damnit, forgot to restart apache, try now

**Comment by mrdsaunders** [comment]
Your fix has worked the data is available in the Sword output. I now need to test the Harvest crosswalk

**Comment by mrdsaunders** [comment]
Tested on deposit (via Sword) and harvest. 

As we originally tested just PMID I have asked Toby to test that PMC and isidoc IDs are also  appearing in forms

**Comment by mrdsaunders** [comment]
Confirmed, will close.

**Comment by mrdsaunders** [comment]
Have also checked NIHMS ID.
