### ISSUE TITLE
Confidential report boolean value still causing errors

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#159]
From Oxris logs:

Technical details:
Fetch attempt last used parameters: 
Exception on machine: NetBIOS name "BSPWIN683", OS "Microsoft Windows NT 6.2.9200.0" (64-bit)
Software instance: Default, Software Version: 5.18.0.2558, Commit Hash: cb314da30988739c811b34142dc9203914d08d99
Command ""D:\Program Files (x86)\Symplectic\Elements\Sync.Synchronise\Synchronise.exe" users" (32-bit)
------------------------------------------------------------------------------------------------------
Log entry ID: d4b37304-cc67-4eed-9d1d-b3b6c4a56b06
Logged at: 10:17:21.510 19/12/19

Level 1:
-------
Exception type: Symplectic.Elements.DataEntities.Sync.SyncException
Message: Crosswalks generated an illegal API import-sync-record document.
Stack trace:
at Symplectic.Elements.Sync.Interop.XwalkInDataSourceClient.ParseXwalkInXml(String, XElement, SyncTechnique) in elements\Sync.Interop\XwalkDataSourceClient.cs:line 513, char 6
at Symplectic.Elements.Sync.Interop.Hyrax.HyraxDataSourceClient.InnerFetch(ICollection<FetchRequest>) in elements\Sync.Interop\Hyrax\HyraxDataSourceClient.cs:line 142, char 5
at Symplectic.Elements.Sync.Processes.FetchWorkItemProcessor.ExecuteFetch(SyncQueueFetchRequestWorkBatch) in elements\Sync.Processes\FetchWorkItemProcessor.cs:line 45, char 5

Level 2:
-------
Exception type: Symplectic.Elements.Api.Service.ErrorHandling.RestArgumentException
Message: CONFIDENTIAL field: could not parse boolean value (Confidential report information goes here!).
Stack trace:
at Symplectic.Elements.Api.Service.XmlGeneration.ApiFieldDeserialiser.ProcessBoolean(Field, XElement) in elements\Api.Service\XmlGeneration\Shared.cs:line 1143, char 5
at Symplectic.Elements.DataEntities.FieldTypeFunc<T1, T2, TResult>.Process(T1, T2) in elements\DataEntities\FieldSerialiser.cs:line 28, char 34
at Symplectic.Elements.Api.Service.Parsing.ApiXmlParsing.LoadFieldValues(Record, ObjectTypeInfo, XElement) in elements\Api.Service\Parsing\ApiXmlParsing.cs:line 697, char 12
at Symplectic.Elements.Api.Service.Parsing.ApiXmlParsing.ParseRecord(CategoryInfo, SourceInfo, String, XElement, Boolean&, Boolean&, ApiObjectIdentifier&) in elements\Api.Service\Parsing\ApiXmlParsing.cs:line 510, char 4
at Symplectic.Elements.Api.Service.Parsing.ApiXmlParsing.ParseImportSyncRecord(SourceInfo, XElement, Boolean&, Boolean&, ApiObjectIdentifier&) in elements\Api.Service\Parsing\ApiXmlParsing.cs:line 427, char 4
at Symplectic.Elements.Sync.Interop.XwalkInDataSourceClient.ParseXwalkInXml(String, XElement, SyncTechnique) in elements\Sync.Interop\XwalkDataSourceClient.cs:line 500, char 4

**Comment by mrdsaunders** [comment]
The issue is non-booleans in ORA `<mods:recordInfoNote type="confidential_report">Confidential report information goes here!</mods:recordInfoNote>`

It seems that the ORA field is text but SE is boolean.

What sort of values are there in the ORA field? Does presence of any data indicate confidential = true perhaps?

**Comment by mrdsaunders** [comment]
In the meantime I have amended the crosswalk to harvest boolean value but ignore others. This will avoid errors.

**Comment by tomwrobel** [comment]
@mrdsaunders your behaviour is pretty much correct. I think the issue here is that ORA expects confidential report to hold a potential value for some items, not just booleans. Please infer any value here as boolean that is a) present and b) not boolean 'false'

**Comment by mrdsaunders** [comment]
`Please infer any value here as boolean that is a) present and b) not boolean 'false'`

So:
any value -> true
false -> no mapping?

**Comment by tomwrobel** [comment]
any value except false -> true
false or no value -> false

**Comment by mrdsaunders** [comment]
Done

**Comment by mrdsaunders** [comment]
Do you have the uuid of an object with a non boolean value for testing? Or @tobypitts  can you amend value to create one?

**Comment by tomwrobel** [comment]
@mrdsaunders try uuid_3bb95008-645e-439e-a64a-435200bfd6d2

**Comment by tomwrobel** [comment]
@mrdsaunders I think this is fixed now? If you need more for testing, please let me know

**Comment by mrdsaunders** [comment]
It is not fixed, as I have to ask AB whether I can used a 'no value' condition in a value map. If not I can rewrite the crosswalk itself to identify if there is a value.

I may have asked this before, but __if this is only relevant to Report/Confidential report__ then there is no need, since it will always be set automatically to 'true'. Are there cases where other output types might be confidential?

**Comment by tomwrobel** [comment]
@mrdsaunders in that case, closing. Many thanks
